name: Download and Unzip luci-app-pxworld.zip

on:
  push:
    branches:
      - main  # یا نام برنچ اصلی شما
    paths:
      - 'luci-app-pxworld.zip'  # فقط زمانی اجرا شود که این فایل تغییر کند
  workflow_dispatch:  # امکان اجرای دستی ورک‌فلو

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download luci-app-pxworld.zip
      run: |
        curl -L -o luci-app-pxworld.zip https://raw.githubusercontent.com/peditx/luci-theme-pxworld/refs/heads/main/luci-app-pxworld.zip

    - name: Unzip luci-app-pxworld.zip
      run: |
        mkdir -p luci-app-pxworld
        unzip luci-app-pxworld.zip -d luci-app-pxworld/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # استفاده از توکن پیش‌فرض GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add luci-app-pxworld/
        git commit -m "Unzipped luci-app-pxworld.zip"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/peditx/luci-theme-pxworld.git
        git push origin main
