name: Unzip luci-app-pxworld.zip

on:
  push:
    branches:
      - main
    paths:
      - 'luci-app-pxworld.zip'
  workflow_dispatch:
    inputs:
      zip_file:
        description: 'نام فایل زیپ'
        required: true
        default: 'luci-app-pxworld.zip'
      branch:
        description: 'برنچ مقصد'
        required: true
        default: 'main'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip file
      run: |
        mkdir -p luci-app-pxworld
        unzip ${{ github.event.inputs.zip_file }} -d luci-app-pxworld/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add luci-app-pxworld/
        git commit -m "Unzipped ${{ github.event.inputs.zip_file }}"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/peditx/luci-theme-pxworld.git
        git push origin ${{ github.event.inputs.branch }}
